#!/bin/bash
#SBATCH --account=uot185
#SBATCH --job-name="imdb"
#SBATCH --output="imdb.local.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=5G
#SBATCH --export=ALL 
#SBATCH --time=10

module load openjdk
SW=/expanse/lustre/projects/uot182/fegaras
export HADOOP_HOME=$SW/hadoop-3.2.2
PATH="$HADOOP_HOME/bin:$PATH"

rm -rf output-wc
hadoop --config $SW/conf jar MainRunner.jar MainRunner title.basics.tsv imdb00-title-actors.csv title.crew.tsv output-wc

